import type { Metadata } from 'next';
import './globals.css';
import '@/styles/app.css';
import CustomThemeProvider from '@/provider/CustomThemeProvider';
import Provider from '@/provider/Provider';

export const metadata: Metadata = {
  title: 'GameTop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <Provider>
          <CustomThemeProvider>{children}</CustomThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
