import type { Metadata } from 'next';
import './globals.css';
import '@/styles/app.css';
import CustomThemeProvider from '@/components/ui-provider/CustomThemeProvider';

export const metadata: Metadata = {
  title: 'GameTop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="dark:bg-background">
        <CustomThemeProvider>{children}</CustomThemeProvider>
      </body>
    </html>
  );
}
